#we are creating a service, headless service and statefulset
#normal service i.e cluster IP service
apiVersion: v1
kind: Service
metadata: 
   name: redis-service  # service name

spec:
  selector:
      project: roboshop
      component: redis
      tier: db
  ports:
     - protocol: TCP
       port: 6379 # sevice port
       targetPort: 6379 # container port   forwart req to another container

---
# this service for headless service
apiVersion: v1
kind: Service
metadata: 
   name: redis-headless-service  # service name
spec:
  clusterIP: None   # this makes headless service
  selector:
      project: roboshop
      component: redis
      tier: db
  ports:
     - protocol: TCP
       port: 6379 # sevice port
       targetPort: 6379 # container port   forwart req to another container       

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-statefulset
  namespace: roboshop
spec:
  serviceName: "redis-headless-service"    # here we need to give headless service name
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: redis
      tier: db

  template:
    metadata:
      labels:
        project: roboshop
        component: redis
        tier: db
    spec:
      containers:
      - name: redis
        image: redis:7.0
        
        volumeMounts:
        - name: redis-claim-vol #volume claimed name
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-claim-vol #volume claim name
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi       

    # above we doing creating volumes with PVC claim name and sending volume name to voume mount see www      